name: Terraform Lint

on: [push, pull_request]

jobs:
  tflint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v2.0.1
      - name: Show tflint version
        run: tflint --version
      - name: Initialize tflint
        run: tflint --init
      - name: Run tflint lint check
        run: tflint -f compact
      - name: Run validation on terraform example 1
        run: |
          cd $GITHUB_WORKSPACE/terraform/hello
          terraform init
          terraform validate
      - name: Run validation on terraform example 2
        run: |
          cd $GITHUB_WORKSPACE/terraform/gcp/components
          terraform init
          terraform validate
